# services:
#   postgres:
#     image: postgres:15-alpine
#     container_name: city-postgres
#     restart: always
#     environment:
#       POSTGRES_DB: citydb
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   app:
#     build: .
#     container_name: city-service
#     restart: on-failure
#     ports:
#       - "8080:8080"
#     depends_on:
#       postgres:
#         condition: service_healthy
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/citydb
#       DB_USERNAME: postgres
#       DB_PASSWORD: postgres

#   broker-message:
#     image: apache/kafka:latest
#     container_name: is-broker-message
#     restart: on-failure
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_PROCESS_ROLES: "broker,controller"
#       KAFKA_NODE_ID: 1
#       KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"

#       KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"

#       KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"

#       KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker-message:9093"

#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#       KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

# volumes:
#   postgres-data:
